language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -e . nose python-coveralls

script:
  - nosetests  --with-coverage --cover-package=erajp

after_success:
  - coveralls
